"""tables

Revision ID: 706ad47223c3
Revises: 19bbad76a7d0
Create Date: 2023-12-03 19:01:57.889600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706ad47223c3'
down_revision = '19bbad76a7d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profiles',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('username', sa.String(), nullable=True, comment='Никнейм пользователя'),
    sa.Column('email', sa.String(), nullable=True, comment='Email пользователя'),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Администратор'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата и время создания'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_profiles_email'), 'users_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_users_profiles_username'), 'users_profiles', ['username'], unique=True)
    op.create_table('external_files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('title', sa.String(), nullable=True, comment='Наименование'),
    sa.Column('file_path', sa.String(), nullable=True, comment='Файл'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='Владелец файла'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата и время создания'),
    sa.ForeignKeyConstraint(['owner_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_files_id'), 'external_files', ['id'], unique=False)
    op.create_index(op.f('ix_external_files_title'), 'external_files', ['title'], unique=False)
    op.create_table('result_files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('title', sa.String(), nullable=True, comment='Наименование'),
    sa.Column('file_path', sa.String(), nullable=True, comment='Файл'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='Владелец файла'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата и время создания'),
    sa.ForeignKeyConstraint(['owner_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_files_id'), 'result_files', ['id'], unique=False)
    op.create_index(op.f('ix_result_files_title'), 'result_files', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_files_title'), table_name='result_files')
    op.drop_index(op.f('ix_result_files_id'), table_name='result_files')
    op.drop_table('result_files')
    op.drop_index(op.f('ix_external_files_title'), table_name='external_files')
    op.drop_index(op.f('ix_external_files_id'), table_name='external_files')
    op.drop_table('external_files')
    op.drop_index(op.f('ix_users_profiles_username'), table_name='users_profiles')
    op.drop_index(op.f('ix_users_profiles_email'), table_name='users_profiles')
    op.drop_table('users_profiles')
    # ### end Alembic commands ###
