"""migration_for_files

Revision ID: c08a774eb303
Revises: 9a8326e5378a
Create Date: 2023-11-30 09:12:58.030318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08a774eb303'
down_revision = '9a8326e5378a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
